USE [GLVData]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GLVSetting_Upload](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UploadType] [nvarchar](30) NULL,
	[ValueSize] [int] NULL,
 CONSTRAINT [PK_Setting_GLVUpload] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO